[package]
name = "anmt"
version = "0.0.2"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
ffprobe = "0.3.3"
json = "0.12.4"
clap = "4.4.16"
rayon = "1.8.0"
